# Generated by Django 5.2.14 on 2026-08-29 11:01

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('sysadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'Audit log',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
