# Generated by Django 5.2.14 on 2026-08-30 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_full_access', models.BooleanField(default=False, help_text='Every power, including creating admins and approving their work.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, help_text='What this person is here to do. Shown in the admin list.', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'admin access',
                'ordering': ['-is_full_access', 'user__display_name'],
            },
        ),
        migrations.CreateModel(
            name='AdminInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.EmailField(max_length=254)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='sysadmin.adminaccess')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'To do'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_tasks_given', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=300)),
                ('post_data', models.JSONField(blank=True, default=dict)),
                ('raw_body', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('amended_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('approved', 'Approved'), ('amended', 'Approved with changes'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, help_text='What the reviewer said. Sent to the author either way.')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_error', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('upload', models.FileField(upload_to='change_requests/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sysadmin.changerequest')),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('admin_created', 'Created an administrator'), ('access_changed', 'Changed what an administrator can do'), ('admin_suspended', 'Suspended an administrator'), ('admin_restored', 'Restored an administrator'), ('invite_sent', 'Sent an invitation'), ('invite_accepted', 'Accepted an invitation'), ('change_requested', 'Submitted work for review'), ('change_approved', 'Approved a change'), ('change_amended', 'Approved a change with edits'), ('change_declined', 'Declined a change'), ('task_assigned', 'Assigned a task'), ('task_completed', 'Completed a task')], max_length=24)),
                ('actor_name', models.CharField(blank=True, max_length=160)),
                ('subject_name', models.CharField(blank=True, max_length=160)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_subject_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sysadmin_ad_created_16d0d1_idx'), models.Index(fields=['action', '-created_at'], name='sysadmin_ad_action_55db75_idx'), models.Index(fields=['subject', '-created_at'], name='sysadmin_ad_subject_ce9b05_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=40)),
                ('requires_approval', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='sysadmin.adminaccess')),
            ],
            options={
                'ordering': ['capability'],
                'constraints': [models.UniqueConstraint(fields=('access', 'capability'), name='uniq_admin_grant')],
            },
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status', '-created_at'], name='sysadmin_ch_status_20b59a_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['requested_by', '-created_at'], name='sysadmin_ch_request_f9ccee_idx'),
        ),
    ]
