# Generated by Django 5.2.14 on 2026-09-20 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0003_adminaccess_admininvite_admintask_changerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default='postmark', max_length=40)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'mail send',
                'verbose_name_plural': 'mail sends',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sysadmin_ma_created_5b371b_idx'), models.Index(fields=['ok', '-created_at'], name='sysadmin_ma_ok_51c5db_idx')],
            },
        ),
    ]
