# Generated by Django 5.2.14 on 2026-06-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_charity'),
        ('orgs', '0010_migrate_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('enterprise_plus', 'Enterprise+')], max_length=20)),
                ('price_aud', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seat_limit', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='orgs.organisation')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='catalog.season')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
