# Generated by Django 5.2.14 on 2026-06-15 11:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0002_charity'),
        ('orgs', '0010_migrate_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledged_amount_aud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount_aud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('payment_schedule', models.CharField(choices=[('lump', 'Lump sum upfront'), ('monthly', 'Monthly instalments'), ('season_close', 'At season close')], default='season_close', max_length=20)),
                ('matching_enabled', models.BooleanField(default=False)),
                ('matching_cap_aud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('matching_used_aud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='catalog.charity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='orgs.organisation')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='catalog.season')),
            ],
        ),
        migrations.CreateModel(
            name='DonationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_aud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('base', 'Org base donation'), ('instalment', 'Org instalment'), ('top_up', 'Participant top-up'), ('matched', 'Org matched amount')], max_length=20)),
                ('paid_by', models.CharField(choices=[('league_owner', 'League Owner'), ('participant', 'Participant'), ('system', 'System (matching)')], max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_payments', to='orgs.organisation')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_payments', to=settings.AUTH_USER_MODEL)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.donationpledge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharityDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_base_aud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_matched_aud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_topups_aud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_disbursed_aud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('receipt_url', models.URLField(blank=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='catalog.charity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='orgs.organisation')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='catalog.season')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('org', 'season'), name='one_disbursement_per_org_season')],
            },
        ),
        migrations.AddConstraint(
            model_name='donationpledge',
            constraint=models.UniqueConstraint(fields=('org', 'season'), name='one_pledge_per_org_season'),
        ),
    ]
