# Generated by Django 5.2.14 on 2026-06-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_donationpledge_donationpayment_charitydisbursement_and_more'),
        ('catalog', '0002_charity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpayment',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donation_payments', to='catalog.charity'),
        ),
    ]
