# Generated by Django 5.2.14 on 2026-07-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_backfill_payment_charity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpayment',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
