# Generated by Django 5.2.14 on 2026-09-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_donationpayment_settled_at'),
        ('orgs', '0050_wallpost_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='is_founding_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='list_price_aud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Team'), ('pro', 'Workplace'), ('enterprise', 'Organisation'), ('enterprise_plus', 'Enterprise+')], max_length=20),
        ),
        migrations.CreateModel(
            name='FoundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Team'), ('pro', 'Workplace'), ('enterprise', 'Organisation'), ('enterprise_plus', 'Enterprise+')], max_length=20)),
                ('price_aud', models.DecimalField(decimal_places=2, max_digits=8)),
                ('locked_until', models.DateField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founding_rate', to='orgs.organisation')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
    ]
