# Generated by Django 5.2.14 on 2026-09-16 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plansubscription_is_founding_rate_and_more'),
        ('catalog', '0020_charity_added_at_charity_added_by_charity_owner_org'),
        ('orgs', '0050_wallpost_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organisation_name', models.CharField(max_length=160)),
                ('organisation_kind', models.CharField(blank=True, max_length=120)),
                ('people', models.PositiveIntegerField(blank=True, help_text='Roughly how many people would be tipping.', null=True)),
                ('reason', models.TextField(help_text='Why the platform fee is out of reach, in their own words.')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Being reviewed'), ('approved', 'Approved'), ('declined', 'Declined')], default='new', max_length=12)),
                ('decision_note', models.TextField(blank=True, help_text='What was decided and why. Shown to nobody but staff.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorship_applications', to='catalog.country')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships_decided', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorship_applications', to='orgs.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
