# Generated by Django 5.2.14 on 2026-10-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_sponsorshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='stripe_invoice_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='stripe_test_clock_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('scheduled', 'Subscribed, billing starts later'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
