# Generated by Django 5.2.14 on 2026-07-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
