# Generated by Django 5.2.14 on 2026-08-05 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_newspost_announced_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('interest', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_page', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10)),
                ('reply_body', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
