# Generated by Django 5.2.14 on 2026-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_newspost_editor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=models.TextField(blank=True, help_text='Rich HTML from the story editor.'),
        ),
    ]
