# Generated by Django 5.2.14 on 2026-08-27 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_newspost_excerpt_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=40)),
                ('slot', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=6)),
                ('file', models.FileField(upload_to='pages/')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_media_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'page media',
                'verbose_name_plural': 'page media',
                'ordering': ['page', 'slot', 'sort_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=80)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_texts_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'page text',
                'verbose_name_plural': 'page text',
                'ordering': ['page', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='uniq_page_text_slot')],
            },
        ),
    ]
