# Generated by Django 5.2.14 on 2026-08-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_pagemedia_pagetext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=140, unique=True)),
                ('text', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('video', models.FileField(blank=True, null=True, upload_to='site/')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_content_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'site content block',
                'verbose_name_plural': 'site content',
                'ordering': ['key'],
            },
        ),
    ]
