# Generated by Django 5.2.14 on 2026-08-30 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_sitecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=40)),
                ('block_key', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('text', 'Wording'), ('image', 'Image')], default='text', max_length=10)),
                ('html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_edits/')),
                ('original_html', models.TextField(blank=True)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page', 'block_key'],
                'indexes': [models.Index(fields=['page'], name='admin_panel_page_046655_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'block_key'), name='uniq_page_edit_block')],
            },
        ),
    ]
