# Generated by Django 5.2.14 on 2026-09-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_seo_fields_multi_tags_and_redirects'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Picture'), ('video', 'Video')], default='image', max_length=5)),
                ('file', models.FileField(upload_to='news/featured/')),
                ('alt', models.CharField(blank=True, help_text='What this one shows, for screen readers and search engines.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='admin_panel.newspost')),
            ],
            options={
                'verbose_name': 'story picture or clip',
                'verbose_name_plural': 'story pictures and clips',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
