# Generated by Django 5.2.14 on 2026-06-03 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('competition', models.CharField(choices=[('AFL', 'AFL'), ('NRL', 'NRL')], max_length=10)),
                ('lockout_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('locked', 'Locked'), ('complete', 'Complete')], default='upcoming', max_length=10)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='orgs.organisation')),
            ],
            options={
                'ordering': ['-round_number'],
                'unique_together': {('org', 'round_number', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('competition', models.CharField(choices=[('AFL', 'AFL'), ('AFLW', 'AFLW'), ('NRL', 'NRL'), ('NRLW', 'NRLW')], max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['competition', 'name'],
                'unique_together': {('slug', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away'), ('draw', 'Draw')], max_length=10, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tipping.round')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='tipping.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='tipping.team')),
            ],
            options={
                'ordering': ['kickoff_at'],
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='tipping.match')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='orgs.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'match', 'org')},
            },
        ),
    ]
