# Generated by Django 5.2.14 on 2026-07-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0005_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='clock',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='live_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='period',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'In play'), ('complete', 'Complete'), ('postponed', 'Postponed')], default='scheduled', max_length=12),
        ),
        migrations.AddField(
            model_name='match',
            name='venue_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'kickoff_at'], name='tipping_mat_status_306048_idx'),
        ),
    ]
