# Generated by Django 5.2.14 on 2026-08-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_industry'),
        ('tipping', '0007_round_results_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('points_for', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_entries', to='catalog.season')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_entries', to='catalog.series')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_entries', to='tipping.team')),
            ],
            options={
                'verbose_name_plural': 'ladder entries',
                'ordering': ['series', 'rank'],
                'unique_together': {('series', 'season', 'team')},
            },
        ),
    ]
