# Generated by Django 5.2.14 on 2026-08-14 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_departmenttype'),
        ('tipping', '0008_ladderentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladderentry',
            name='byes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LadderAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Negative to deduct, e.g. -12 for a salary-cap penalty.')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_adjustments', to='catalog.season')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_adjustments', to='catalog.series')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_adjustments', to='tipping.team')),
            ],
            options={
                'ordering': ['series', 'team'],
            },
        ),
    ]
