# Generated by Django 5.2.14 on 2026-08-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0010_merge_duplicate_gws_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
