# Generated by Django 5.2.14 on 2026-08-20 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0033_organisation_groups_enabled_group_groupmember_and_more'),
        ('tipping', '0011_tip_is_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tip',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='orgs.group'),
        ),
        migrations.AddConstraint(
            model_name='tip',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('user', 'match', 'org', 'group'), name='uniq_tip_per_group'),
        ),
        migrations.AddConstraint(
            model_name='tip',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True)), fields=('user', 'match', 'org'), name='uniq_tip_per_org'),
        ),
    ]
