# Generated by Django 5.2.14 on 2026-09-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipping', '0012_alter_tip_unique_together_tip_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['kickoff_at'], 'verbose_name_plural': 'matches'},
        ),
    ]
