# Generated by Django 5.2.14 on 2026-10-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_hide_gamblers_help'),
        ('orgs', '0052_message_edit_delete_and_wall_edits'),
        ('tipping', '0013_alter_match_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificate_photos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_photos', to='orgs.organisation')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.series')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('org', 'series', 'user')},
            },
        ),
    ]
