# Generated by Django 5.2.14 on 2026-06-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_use_catalog_lookups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='finals_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
