# Generated by Django 5.2.14 on 2026-06-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_charity'),
        ('orgs', '0004_orgmember_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisations', to='catalog.charity'),
        ),
    ]
