# Generated by Django 5.2.14 on 2026-06-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_populate_charities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='charity_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='charity_url',
        ),
    ]
