# Generated by Django 5.2.14 on 2026-06-12 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_charity'),
        ('orgs', '0007_remove_organisation_charity_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_votes', to='orgs.organisation')),
                ('winning_charity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_charity_votes', to='catalog.charity')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CharityVoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_options', to='catalog.charity')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orgs.charityvote')),
            ],
            options={
                'ordering': ['charity__name'],
                'unique_together': {('vote', 'charity')},
            },
        ),
        migrations.CreateModel(
            name='CharityVoteBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_ballots', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='orgs.charityvote')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='orgs.charityvoteoption')),
            ],
            options={
                'unique_together': {('vote', 'user')},
            },
        ),
    ]
