# Generated by Django 5.2.14 on 2026-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_charityvote_charityvoteoption_charityvoteballot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='is_league_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='role',
            field=models.CharField(choices=[('manager', 'Team Manager'), ('captain', 'Captain'), ('both', 'Manager & Captain'), ('participant', 'Participant')], default='participant', max_length=12),
        ),
    ]
