# Generated by Django 5.2.14 on 2026-06-17 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_charity'),
        ('orgs', '0010_migrate_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgCharitySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('initial', 'Set at league creation'), ('vote', 'Won the charity vote'), ('manual', 'Changed manually')], default='manual', max_length=10)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='catalog.charity')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_selections', to='orgs.organisation')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charity_selections', to='catalog.season')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
    ]
