# Generated by Django 5.2.14 on 2026-07-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_org_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcharityselection',
            name='source',
            field=models.CharField(choices=[('initial', 'Set at league creation'), ('vote', 'Won the charity vote'), ('manual', 'Changed manually'), ('self', 'Locked to own charity')], default='manual', max_length=10),
        ),
    ]
