# Generated by Django 5.2.14 on 2026-07-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_alter_orgcharityselection_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='orgs.organisation'),
        ),
    ]
