# Generated by Django 5.2.14 on 2026-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_charityvote_admin_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityvote',
            name='scheduled_close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
