# Generated by Django 5.2.14 on 2026-07-17 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_charityvote_scheduled_close_at'),
        ('tipping', '0005_team_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WallPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('member', 'Member post'), ('system', 'GoodTip update'), ('recap', 'AI Group Recap')], default='member', max_length=10)),
                ('body', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts', to='orgs.organisation')),
                ('tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_posts', to='tipping.tip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WallReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('fire', '🔥'), ('laugh', '😂'), ('heart', '❤️'), ('clap', '👏'), ('eyes', '👀')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='orgs.wallpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='wallpost',
            index=models.Index(fields=['org', '-created_at'], name='orgs_wallpo_org_id_001c52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wallreaction',
            unique_together={('post', 'user', 'emoji')},
        ),
    ]
