# Generated by Django 5.2.14 on 2026-07-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_wallpost_wallreaction_and_more'),
        ('tipping', '0005_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallback_used', models.BooleanField(default=False)),
                ('model_used', models.CharField(blank=True, max_length=60)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_recaps', to='orgs.organisation')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recap', to='orgs.wallpost')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaps', to='tipping.round')),
            ],
            options={
                'unique_together': {('org', 'round')},
            },
        ),
    ]
