# Generated by Django 5.2.14 on 2026-07-24 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_roundrecap'),
        ('tipping', '0005_team_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WallReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=80)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'wall replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='wallpost',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('election_open', 'Charity election open'), ('election_result', 'Charity election result'), ('admin_note', 'Note from your admin'), ('wall_reply', 'Reply to your post'), ('wall_post', 'New post on your Wall')], default='admin_note', max_length=20),
        ),
        migrations.AddIndex(
            model_name='wallpost',
            index=models.Index(fields=['is_public', '-created_at'], name='orgs_wallpo_is_publ_6f356f_idx'),
        ),
        migrations.AddField(
            model_name='wallreply',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallreply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='orgs.wallpost'),
        ),
        migrations.AddIndex(
            model_name='wallreply',
            index=models.Index(fields=['post', 'created_at'], name='orgs_wallre_post_id_673e0d_idx'),
        ),
    ]
