# Generated by Django 5.2.14 on 2026-07-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_wallreply_wallpost_is_public_alter_notification_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityvote',
            name='reminder_day_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityvote',
            name='reminder_hour_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityvote',
            name='result_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
