# Generated by Django 5.2.14 on 2026-07-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_charityvote_reminder_day_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('election_open', 'Charity election open'), ('election_result', 'Charity election result'), ('election_sched', 'Charity election scheduled'), ('admin_note', 'Note from your admin'), ('wall_reply', 'Reply to your post'), ('wall_post', 'New post on your Wall'), ('join_requested', 'Join request sent'), ('join_review', 'Join request to review'), ('join_approved', 'Join request approved'), ('join_declined', 'Join request declined')], default='admin_note', max_length=20),
        ),
    ]
