# Generated by Django 5.2.14 on 2026-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_orgdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, upload_to='org_logos/'),
        ),
    ]
