# Generated by Django 5.2.14 on 2026-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_organisation_contact_role_organisation_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrecap',
            name='leaderboard',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roundrecap',
            name='talking_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
