# Generated by Django 5.2.14 on 2026-08-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_subcategory_options_and_more'),
        ('orgs', '0035_rename_group_type_and_drop_department_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='catalog.grouptype'),
        ),
    ]
