# Generated by Django 5.2.14 on 2026-08-20 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0036_alter_group_kind'),
        ('tipping', '0012_alter_tip_unique_together_tip_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_posts', to='orgs.group'),
        ),
        migrations.AddIndex(
            model_name='wallpost',
            index=models.Index(fields=['group', '-created_at'], name='orgs_wallpo_group_i_34b40c_idx'),
        ),
    ]
