# Generated by Django 5.2.14 on 2026-08-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0037_wallpost_group_and_more'),
        ('tipping', '0012_alter_tip_unique_together_tip_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roundrecap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roundrecap',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_recaps', to='orgs.group'),
        ),
        migrations.AddConstraint(
            model_name='roundrecap',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('org', 'round', 'group'), name='uniq_recap_per_group_round'),
        ),
        migrations.AddConstraint(
            model_name='roundrecap',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True)), fields=('org', 'round'), name='uniq_recap_per_org_round'),
        ),
    ]
