# Generated by Django 5.2.14 on 2026-08-26 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_alter_roundrecap_unique_together_roundrecap_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charityvote',
            name='tie_broken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charityvote',
            name='tie_broken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charity_ties_broken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charityvote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('open', 'Open'), ('tied', "Tied — awaiting captain's call"), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('election_open', 'Charity election open'), ('election_result', 'Charity election result'), ('election_sched', 'Charity election scheduled'), ('election_tied', 'Charity election tied'), ('admin_note', 'Note from your admin'), ('wall_reply', 'Reply to your post'), ('wall_post', 'New post on your Wall'), ('join_requested', 'Join request sent'), ('join_review', 'Join request to review'), ('join_approved', 'Join request approved'), ('join_declined', 'Join request declined')], default='admin_note', max_length=20),
        ),
    ]
