# Generated by Django 5.2.14 on 2026-08-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_country'),
        ('orgs', '0039_charityvote_tie_broken_at_charityvote_tie_broken_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='catalog.country'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to='catalog.country'),
        ),
    ]
