# Generated by Django 5.2.14 on 2026-08-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_charity_added_at_charity_added_by_charity_owner_org'),
        ('orgs', '0041_default_existing_orgs_to_australia'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityvote',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charity_votes', to='orgs.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backing_groups', to='catalog.charity'),
        ),
        migrations.AddField(
            model_name='orgcharityselection',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charity_selections', to='orgs.group'),
        ),
    ]
