# Generated by Django 5.2.14 on 2026-08-31 11:59

import django.db.models.deletion
import django.utils.timezone
import orgs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0043_messagethread_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='orgs.message'),
        ),
        migrations.AddField(
            model_name='wallreply',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='orgs.wallreply'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=orgs.models.message_attachment_path)),
                ('original_name', models.CharField(max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orgs.message')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
