# Generated by Django 5.2.14 on 2026-09-03 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0045_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='duration_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='is_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orgs.message'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='kind',
            field=models.CharField(choices=[('raised', 'Raised by a member'), ('notice', 'Sent by an admin'), ('org', 'Organisation room'), ('group', 'Group room'), ('direct', 'Direct message')], default='raised', max_length=10),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='orgs.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='uniq_message_reaction')],
            },
        ),
    ]
