# Generated by Django 5.2.14 on 2026-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0046_chat_rooms_voice_notes_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
