# Generated by Django 5.2.14 on 2026-09-05 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0047_notification_announced_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('terms', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True, help_text="What the reporter said, or the reviewer's note.")),
                ('status', models.CharField(choices=[('open', 'Waiting for review'), ('cleared', 'Not an issue'), ('actioned', 'Actioned')], default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_messages', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='orgs.message')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_flags', to='orgs.organisation')),
                ('raised_by', models.ForeignKey(blank=True, help_text='The member who reported it. Empty means Prefect found it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_flags', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('warning', 'Warning'), ('suspension', 'Suspended from posting')], default='warning', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Empty means it runs until somebody lifts it.', null=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions', to='orgs.chatflag')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='orgs.group')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sanctions', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_sanctions', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='orgs.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrefectAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefect_allowances', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefect_allowances', to='orgs.organisation')),
            ],
            options={
                'ordering': ['phrase'],
            },
        ),
        migrations.AddIndex(
            model_name='chatflag',
            index=models.Index(fields=['org', 'status'], name='orgs_chatfl_org_id_c7b624_idx'),
        ),
        migrations.AddIndex(
            model_name='membersanction',
            index=models.Index(fields=['org', 'user', 'kind'], name='orgs_member_org_id_cb2e3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prefectallowance',
            unique_together={('org', 'phrase')},
        ),
    ]
