# Generated by Django 5.2.14 on 2026-09-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_charity_added_at_charity_added_by_charity_owner_org'),
        ('orgs', '0049_memberblock_threadpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_posts', to='catalog.series'),
        ),
    ]
