# Generated by Django 5.2.14 on 2026-07-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('current_platform', models.CharField(blank=True, choices=[('footytips', 'footytips (ESPN)'), ('afl', 'Official AFL Tipping'), ('nrl', 'Official NRL Tipping'), ('supercoach', 'SuperCoach Tips'), ('itipfooty', 'iTipFooty'), ('other', 'Another platform'), ('none', "We don't run a tipping comp yet"), ('na', 'Prefer not to say')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
