# Generated by Django 5.2.14 on 2026-08-04 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified_at_user_two_factor_enabled_and_more'),
        ('orgs', '0027_organisation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(blank=True, max_length=80)),
                ('boss_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body_preview', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Note sent'), ('joined', 'Boss signed up'), ('complete', 'Group created')], default='sent', max_length=10)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('boss_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_invites_received', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_boss_invites', to='orgs.organisation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['boss_email', 'status'], name='accounts_bo_boss_em_79abad_idx')],
            },
        ),
    ]
