# Generated by Django 5.2.14 on 2026-08-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bossinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tip_carry_mode',
            field=models.CharField(choices=[('ask', 'Ask me each time'), ('all', "Always carry my tips to every group I'm in"), ('none', "Only ever tip the group I'm in")], default='ask', max_length=5),
        ),
    ]
