# Generated by Django 5.2.14 on 2026-08-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_tip_carry_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
