# Generated by Django 5.2.14 on 2026-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_onboarding_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Sign-in verification'), ('signup', 'Email verification at signup'), ('admin', 'Admin access verification')], default='login', max_length=10),
        ),
    ]
