# Generated by Django 5.2.14 on 2026-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_logincode_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_pages_seen',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
