# Generated by Django 5.2.14 on 2026-09-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_recap_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchsignup',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launchsignup',
            name='org_type',
            field=models.CharField(blank=True, choices=[('business', 'Business or workplace'), ('community', 'Community group or sports club'), ('education', 'School or university'), ('charities', 'Charity or not-for-profit'), ('informal', 'Group of mates')], max_length=20),
        ),
        migrations.AddField(
            model_name='launchsignup',
            name='source_page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
