#!/bin/bash
# Stand up staging.goodtip.com.au on this box. Idempotent: safe to re-run.
#
#   sudo bash deploy/bootstrap-staging.sh
#
# Creates a second checkout of this repo tracking the `staging` branch, with its
# own virtualenv, its own .env, its own database, its own gunicorn on :8001 and
# its own two-minute deploy timer. Production is not touched: nothing here
# writes to the production checkout, the production database, the production
# units or the production vhost.
#
# It does NOT populate the database with anything. Run deploy/refresh-staging-db.sh
# afterwards to fill it from a scrubbed copy of production.
set -euo pipefail

REPO="${REPO:-git@github.com:waitambatha/goodtip.git}"
BRANCH="${BRANCH:-staging}"
PROD_DIR="${PROD_DIR:-/home/mbatha-goodtip/projects/goodtip}"
STAGING_DIR="${STAGING_DIR:-/home/mbatha-goodtip/projects/goodtip-staging}"
APP_USER="${APP_USER:-mbatha-goodtip}"
STAGING_DB="${STAGING_DB:-goodtip_staging_db}"
DB_OWNER="${DB_OWNER:-goodtip_user}"
DOMAIN="${DOMAIN:-staging.goodtip.com.au}"
UNIT_DST=/etc/systemd/system

if [ "$(id -u)" -ne 0 ]; then
  echo "Run with sudo: sudo bash deploy/bootstrap-staging.sh" >&2
  exit 1
fi
if [ "$(readlink -f "$STAGING_DIR")" = "$(readlink -f "$PROD_DIR")" ]; then
  echo "ERROR: STAGING_DIR and PROD_DIR are the same directory." >&2
  exit 1
fi

as_app() { sudo -u "$APP_USER" bash -c "$1"; }

# --- 1. checkout -------------------------------------------------------------
if [ ! -d "$STAGING_DIR/.git" ]; then
  echo "==> cloning $BRANCH into $STAGING_DIR"
  install -d -o "$APP_USER" -g "$APP_USER" "$(dirname "$STAGING_DIR")"
  as_app "git clone --branch '$BRANCH' '$REPO' '$STAGING_DIR'"
else
  echo "==> checkout exists; fetching"
  as_app "cd '$STAGING_DIR' && git fetch origin '$BRANCH' && git checkout '$BRANCH' && git reset --hard 'origin/$BRANCH'"
fi

# --- 2. virtualenv -----------------------------------------------------------
if [ ! -x "$STAGING_DIR/venv/bin/python" ]; then
  echo "==> creating virtualenv"
  as_app "python3 -m venv '$STAGING_DIR/venv'"
fi
echo "==> installing dependencies"
as_app "'$STAGING_DIR/venv/bin/pip' install -q --upgrade pip && '$STAGING_DIR/venv/bin/pip' install -q -r '$STAGING_DIR/requirements.txt'"

# --- 3. database -------------------------------------------------------------
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$STAGING_DB'" | grep -q 1; then
  echo "==> creating database $STAGING_DB"
  sudo -u postgres createdb -O "$DB_OWNER" "$STAGING_DB"
else
  echo "==> database $STAGING_DB already exists; leaving it alone"
fi

# --- 4. .env -----------------------------------------------------------------
# Written once and never overwritten: after the first run this file holds a
# generated SECRET_KEY and a gate password someone has already given the client.
if [ ! -f "$STAGING_DIR/.env" ]; then
  echo "==> writing $STAGING_DIR/.env"

  # A SECRET_KEY of its own, not production's. Django signs session cookies,
  # password-reset tokens and the staging gate cookie with it, so sharing the
  # key would make a session minted on staging valid on goodtip.com.au -- the
  # staging gate would then be the only thing standing between a demo password
  # and a signed-in production session.
  SECRET=$(as_app "'$STAGING_DIR/venv/bin/python' -c \"from django.core.management.utils import get_random_secret_key as k; print(k())\"")
  GATE_PW=$(head -c 12 /dev/urandom | base64 | tr -d '/+=' | head -c 12)

  # Carry the third-party credentials over from production's .env rather than
  # asking for them again -- same box, same user, and staging genuinely needs a
  # working Postmark token to preview an invite email. What makes that safe is
  # EMAIL_ALLOWLIST below, not the absence of a token.
  carry() { grep -m1 "^$1=" "$PROD_DIR/.env" 2>/dev/null || echo "$1="; }

  cat > "$STAGING_DIR/.env" <<ENV
# staging.goodtip.com.au — generated by deploy/bootstrap-staging.sh.
# Deliberately NOT a copy of production's .env. See the comments on each block.

GOODTIP_ENV=staging
DEBUG=False
SECRET_KEY=$SECRET

# Staging's own database. Nothing else in this file matters as much as this
# line: point it at goodtip_db and a staging migration alters the live site.
DATABASE_URL=postgres://$DB_OWNER:CHANGE_ME@localhost:5432/$STAGING_DB

ALLOWED_HOSTS=$DOMAIN
CSRF_TRUSTED_ORIGINS=https://$DOMAIN
SITE_BASE_URL=https://$DOMAIN

# The branded lock page (goodtip/staging_gate.py). Give the client the second
# pair; change either by editing this line and restarting the service.
STAGING_GATE=True
STAGING_GATE_USERS=team:$GATE_PW,client:$GATE_PW

# Who staging is allowed to email. Everything to any other address is logged
# and dropped by AllowlistEmailBackend. Empty means nothing goes out at all,
# which is the right default until someone decides otherwise -- staging runs on
# a copy of the real membership, so "email all members" is a live code path.
EMAIL_ALLOWLIST=

# Scheduled jobs stay off: match sync and the nightly jobs would double the
# scraping this box does and race production for the same upstream pages.
AUTOSYNC_ENABLED=False

$(carry POSTMARK_SERVER_TOKEN)
$(carry DEFAULT_FROM_EMAIL)
$(carry GOODTIP_TEAM_EMAIL)

# Stripe: left blank on purpose so billing stays dormant. Put TEST keys here if
# a checkout flow needs demonstrating -- never the live ones.
STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=
ENV
  chown "$APP_USER:$APP_USER" "$STAGING_DIR/.env"
  chmod 600 "$STAGING_DIR/.env"
  echo
  echo "    !! Set the database password in $STAGING_DIR/.env (DATABASE_URL, CHANGE_ME)."
  echo "    !! Staging gate password: $GATE_PW  (users: team, client)"
  echo
else
  echo "==> $STAGING_DIR/.env exists; leaving it alone"
fi

# --- 5. django ---------------------------------------------------------------
echo "==> migrate + collectstatic"
as_app "cd '$STAGING_DIR' && venv/bin/python manage.py migrate --noinput && venv/bin/python manage.py collectstatic --noinput" \
  || { echo "ERROR: Django could not start. Check DATABASE_URL in $STAGING_DIR/.env." >&2; exit 1; }

# --- 6. systemd --------------------------------------------------------------
# Staging's two units only. install-timers.sh is production's and refuses to run
# from here; the scheduled-job timers are deliberately not installed for staging.
echo "==> installing staging units"
for unit in goodtip-staging.service goodtip-staging-sync.service goodtip-staging-sync.timer; do
  install -m 644 "$STAGING_DIR/deploy/systemd/$unit" "$UNIT_DST/$unit"
done
systemctl daemon-reload
systemctl enable --now goodtip-staging.service
systemctl enable --now goodtip-staging-sync.timer

# --- 7. nginx ----------------------------------------------------------------
echo "==> installing nginx vhost"
# Never clobber a certbot-modified vhost: after certbot runs, this file holds
# the :443 block and the certificate paths, and reinstalling the plain HTTP
# version would take TLS off the site on the next re-run of this script.
if [ -f "/etc/nginx/sites-available/$DOMAIN" ] && grep -q "listen 443" "/etc/nginx/sites-available/$DOMAIN"; then
  echo "    vhost already has TLS configured; leaving it alone"
else
  install -m 644 "$STAGING_DIR/deploy/nginx/$DOMAIN.conf" "/etc/nginx/sites-available/$DOMAIN"
  ln -sfn "/etc/nginx/sites-available/$DOMAIN" "/etc/nginx/sites-enabled/$DOMAIN"
fi
nginx -t
systemctl reload nginx

# --- 8. tls ------------------------------------------------------------------
if [ ! -d "/etc/letsencrypt/live/$DOMAIN" ]; then
  echo "==> requesting certificate for $DOMAIN"
  if command -v certbot >/dev/null; then
    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
      --register-unsafely-without-email --redirect \
      || echo "WARNING: certbot failed. Site is up on HTTP; re-run: certbot --nginx -d $DOMAIN" >&2
  else
    echo "WARNING: certbot not installed. Site is HTTP-only until it is." >&2
  fi
else
  echo "==> certificate already present"
fi

echo
echo "=============================================================="
systemctl is-active goodtip-staging.service goodtip-staging-sync.timer || true
echo
echo "Staging is up at https://$DOMAIN (branch: $BRANCH)."
echo "It has an empty database. Fill it with a scrubbed copy of production:"
echo
echo "  sudo bash $STAGING_DIR/deploy/refresh-staging-db.sh --keep you@example.com"
echo "=============================================================="
