"""ESG report export for Pro+ leagues (Cost Structure deck slide 7).

Season summary: participants, rounds, total charity distributed, charity
breakdown, and matching contribution — exportable as a PDF.
"""
from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from . import donations
from .pricing import ENTERPRISE, ENTERPRISE_PLUS, PRO
from .services import active_subscription

# Tiers that unlock ESG export (deck: "ESG report export" is a Pro+ feature).
ESG_TIERS = {PRO, ENTERPRISE, ENTERPRISE_PLUS}

ACCENT = colors.HexColor("#2D7A3A")
INK = colors.HexColor("#0D1A11")


def esg_export_allowed(org) -> bool:
    sub = active_subscription(org)
    return bool(sub and sub.tier in ESG_TIERS)


def build_esg_context(org) -> dict:
    from tipping.models import Round

    summary = donations.donation_summary(org)
    rounds = Round.objects.filter(org=org)
    disbursement = org.disbursements.filter(season=org.season).first()
    return {
        "org": org,
        "charity": (summary["charity"] if summary else None) or org.charity,
        "participants": org.members.count(),
        "rounds_total": rounds.count(),
        "rounds_complete": rounds.filter(status="complete").count(),
        "summary": summary,
        "disbursement": disbursement,
    }


def build_esg_pdf(org) -> bytes:
    ctx = build_esg_context(org)
    summary = ctx["summary"]
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
        title=f"GoodTip ESG Report — {org.name}",
    )
    styles = getSampleStyleSheet()
    h1 = styles["Title"]
    h1.textColor = ACCENT
    body = styles["BodyText"]
    micro = styles["Normal"].clone("micro")
    micro.fontSize = 9
    micro.textColor = colors.grey

    charity_name = ctx["charity"].name if ctx["charity"] else "—"
    elements = [
        Paragraph("GoodTip ESG Report", h1),
        Paragraph(f"{org.name} &nbsp;·&nbsp; {org.season} season", micro),
        Spacer(1, 8 * mm),
        Paragraph(f"Charitable beneficiary: <b>{charity_name}</b>", body),
        Spacer(1, 4 * mm),
    ]

    overview = [
        ["Participants", str(ctx["participants"])],
        ["Rounds played", f"{ctx['rounds_complete']} of {ctx['rounds_total']} complete"],
        ["Sports", org.sport_label],
    ]
    elements += _table(overview, "Engagement")

    if summary:
        money = [
            ["Org base donation", _aud(summary["base"])],
            ["Participant top-ups", _aud(summary["topups"])],
            ["Org matched contribution", _aud(summary["matched"])],
            ["Total raised for charity", _aud(summary["raised"])],
        ]
        elements += _table(money, "Charity breakdown", total_row=True)
        if ctx["disbursement"]:
            d = ctx["disbursement"]
            elements.append(Spacer(1, 4 * mm))
            elements.append(Paragraph(
                f"Settled for disbursement: <b>{_aud(d.total_disbursed_aud)}</b> "
                f"on {d.disbursed_at:%d %b %Y}." if d.disbursed_at else "",
                body,
            ))
    else:
        elements.append(Paragraph("No donation pledge was recorded for this season.", body))

    elements.append(Spacer(1, 12 * mm))
    elements.append(Paragraph(
        "Generated by GoodTip. Figures cover the platform's charitable activity for the "
        "season shown. Platform service fees are excluded — this report reflects charity "
        "impact only.", micro,
    ))

    doc.build(elements)
    return buf.getvalue()


def _aud(value) -> str:
    return f"${value:,.2f}"


def _table(rows, heading, *, total_row=False):
    data = [[heading, ""]] + rows
    t = Table(data, colWidths=[90 * mm, 60 * mm])
    style = [
        ("SPAN", (0, 0), (1, 0)),
        ("BACKGROUND", (0, 0), (1, 0), INK),
        ("TEXTCOLOR", (0, 0), (1, 0), colors.white),
        ("FONTNAME", (0, 0), (1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 1), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("ALIGN", (1, 1), (1, -1), "RIGHT"),
    ]
    if total_row:
        style += [
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, -1), (-1, -1), ACCENT),
        ]
    t.setStyle(TableStyle(style))
    return [Spacer(1, 4 * mm), t]
