# Generated by Django 5.2.14 on 2026-08-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_the_two_type_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['organisation_type__sort_order', 'sort_order', 'name'], 'verbose_name_plural': 'sub-categories'},
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='uniq_subcategory_slug_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='uniq_subcategory_name_per_type',
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='organisation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_types', to='catalog.organisationtype'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('organisation_type', 'slug'), name='uniq_subcategory_slug_per_type'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('organisation_type', 'name'), name='uniq_subcategory_name_per_type'),
        ),
    ]
