# Generated by Django 5.2.14 on 2026-08-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='logo',
            field=models.ImageField(blank=True, upload_to='charity_logos/'),
        ),
        migrations.AddField(
            model_name='charity',
            name='logo_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
