# Generated by Django 5.2.14 on 2026-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_charity_logo_charity_logo_fetched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('segment', models.CharField(choices=[('australia', 'Australia'), ('new_zealand', 'New Zealand'), ('global', 'Global')], default='global', max_length=12)),
                ('is_pacific', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
