# Generated by Django 5.2.14 on 2026-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_seed_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationtype',
            name='is_formal',
            field=models.BooleanField(default=True, help_text='Formal: workplace, school, club, registered entity. Informal: mates, family, community group.'),
        ),
    ]
