# Generated by Django 5.2.14 on 2026-08-27 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_fold_nz_into_australia_segment'),
        ('orgs', '0041_default_existing_orgs_to_australia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charities_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charity',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_charities', to='orgs.organisation'),
        ),
    ]
