# Generated by Django 5.2.14 on 2026-09-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_charity_added_at_charity_added_by_charity_owner_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide from all pickers without deleting. Existing selections are unaffected.'),
        ),
    ]
