# Generated by Django 5.2.14 on 2026-08-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0010_departmenttype'),
        ('tipping', '0008_ladderentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intercept', models.FloatField()),
                ('form_coef', models.FloatField()),
                ('exp_coef', models.FloatField(blank=True, null=True)),
                ('train_seasons', models.CharField(max_length=100)),
                ('test_seasons', models.CharField(max_length=100)),
                ('train_samples', models.PositiveIntegerField()),
                ('test_samples', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('baseline_accuracy', models.FloatField(help_text='Always-pick-home accuracy on the same test set. A model that cannot beat this is not worth shipping.')),
                ('is_active', models.BooleanField(default=False)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchreader_models', to='catalog.series')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('round_number', models.PositiveIntegerField()),
                ('external_id', models.CharField(max_length=100)),
                ('kickoff_at', models.DateTimeField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_away', to='tipping.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_home', to='tipping.team')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_matches', to='catalog.series')),
            ],
            options={
                'ordering': ['kickoff_at'],
                'indexes': [models.Index(fields=['series', 'season', 'round_number'], name='matchreader_series__06033d_idx'), models.Index(fields=['kickoff_at'], name='matchreader_kickoff_57f84b_idx')],
                'unique_together': {('series', 'external_id')},
            },
        ),
    ]
