# Generated by Django 5.2.14 on 2026-07-27 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0023_wallreply_wallpost_is_public_alter_notification_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fixtures', 'Fixtures'), ('results', 'Results'), ('live', 'Live scores')], max_length=10)),
                ('competition', models.CharField(max_length=20)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('matches_touched', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='orgs.organisation')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['kind', '-started_at'], name='data_sync_s_kind_6b58e3_idx')],
            },
        ),
    ]
