# Generated by Django 5.2.14 on 2026-08-04 11:55

import django.utils.timezone
from django.db import migrations, models


def seed_kinds(apps, schema_editor):
    """One row per sync kind, due immediately.

    The claim is an UPDATE, which matches nothing if the row is absent — so
    without this the scheduler would sit silently doing nothing forever.
    """
    SyncSchedule = apps.get_model("data_sync", "SyncSchedule")
    for kind in ("live", "results", "fixtures"):
        SyncSchedule.objects.get_or_create(kind=kind)


def unseed(apps, schema_editor):
    apps.get_model("data_sync", "SyncSchedule").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fixtures', 'Fixtures'), ('results', 'Results'), ('live', 'Live scores')], max_length=10, unique=True)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.RunPython(seed_kinds, unseed),
    ]
