# Generated by Django 5.2.14 on 2026-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0002_syncschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrun',
            name='kind',
            field=models.CharField(choices=[('fixtures', 'Fixtures'), ('results', 'Results'), ('live', 'Live scores'), ('ladder', 'Ladder')], max_length=10),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='kind',
            field=models.CharField(choices=[('fixtures', 'Fixtures'), ('results', 'Results'), ('live', 'Live scores'), ('ladder', 'Ladder')], max_length=10, unique=True),
        ),
    ]
