# Generated by Django 5.2.14 on 2026-08-16 17:40

from django.db import migrations, models


def seed_kinds(apps, schema_editor):
    """A SyncSchedule row for every kind the scheduler knows about.

    Claiming a kind is an UPDATE, and an UPDATE matches nothing when the row is
    absent — so a kind with no row here is simply never run, silently and
    forever. That already happened once: "ladder" was added to the choices in
    0003 without a row, and standings only ran at all because somebody created
    it by hand later.

    get_or_create over every kind, so this is both the fix for "backfill" and a
    backstop against the next one.
    """
    SyncSchedule = apps.get_model("data_sync", "SyncSchedule")
    for kind in ("fixtures", "results", "live", "ladder", "backfill"):
        SyncSchedule.objects.get_or_create(kind=kind)


def unseed(apps, schema_editor):
    apps.get_model("data_sync", "SyncSchedule").objects.filter(kind="backfill").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0003_alter_syncrun_kind_alter_syncschedule_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrun',
            name='kind',
            field=models.CharField(choices=[('fixtures', 'Fixtures'), ('results', 'Results'), ('live', 'Live scores'), ('ladder', 'Ladder'), ('backfill', 'Full-season backfill')], max_length=10),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='kind',
            field=models.CharField(choices=[('fixtures', 'Fixtures'), ('results', 'Results'), ('live', 'Live scores'), ('ladder', 'Ladder'), ('backfill', 'Full-season backfill')], max_length=10, unique=True),
        ),
        migrations.RunPython(seed_kinds, unseed),
    ]
