# Generated by Django 5.2.14 on 2026-08-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sync', '0004_alter_syncrun_kind_alter_syncschedule_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('series_key', models.CharField(max_length=60)),
                ('season_year', models.PositiveIntegerField()),
                ('round_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='data_sync_f_fetched_393bfc_idx')],
                'unique_together': {('source', 'series_key', 'season_year', 'round_number')},
            },
        ),
    ]
